export type Era = {
  id: string;
  years: string;
  title: string;
  kicker: string;
  palette: { bg: string; accent: string; text: string; soft: string; glass: string };
  fontFamily: "rounded" | "geometric";
  narrative: string[];
  artifact: { label: string; title: string; detail: string; glyph: string };
};

export const eras: Era[] = [
  { id: "garage", years: "1976—1980", title: "Built from first principles", kicker: "The garage era", palette: { bg: "#d9c7a9", accent: "#ef6b3c", text: "#1c211d", soft: "#efe4d0", glass: "rgba(214, 199, 168, 0.72)" }, fontFamily: "rounded", narrative: ["Two Steves began with a circuit board, a borrowed garage, and a belief that a computer could belong on a desk instead of behind a lab door.", "The first machines were assembled by hand. Their rough edges were part of the point: a new kind of company was learning that technology could feel personal before it looked polished."], artifact: { label: "ARCHIVE / 01", title: "The first board", detail: "1976 · 30 assembled boards · one improbable beginning", glyph: "▦" } },
  { id: "macintosh", years: "1984", title: "A different kind of machine", kicker: "The interface arrives", palette: { bg: "#d7d5ce", accent: "#e14e3b", text: "#242525", soft: "#f4f2ed", glass: "rgba(215, 213, 206, 0.72)" }, fontFamily: "geometric", narrative: ["In 1984, the Macintosh made the screen feel less like a command center and more like a room you could enter. Windows, menus, and a small pointer turned instructions into gestures.", "The breakthrough was not only technical. It was a wager on clarity: that people would choose a computer when it met them at eye level."], artifact: { label: "SYSTEM / 1.0", title: "A desktop you could enter", detail: "1984 · 9-inch screen · 128 KB memory", glyph: "⌘" } },
  { id: "imac", years: "1998", title: "Color returns", kicker: "The translucent reset", palette: { bg: "#a9d8e7", accent: "#0f718f", text: "#092a35", soft: "#dcf4f7", glass: "rgba(169, 216, 231, 0.72)" }, fontFamily: "geometric", narrative: ["The iMac arrived like a bright object from a friendlier future: translucent, compact, and unapologetically blue. It made the computer a visible part of the room again.", "Removing the floppy drive was a quiet act of confidence. The design asked people to let go of one habit in exchange for a simpler way in."], artifact: { label: "OBJECT / 98", title: "Bondi blue, on purpose", detail: "1998 · translucent shell · 15-inch display", glyph: "◉" } },
  { id: "pocket", years: "2001—2007", title: "The pocket revolution", kicker: "A thousand songs, then a world", palette: { bg: "#c7c9cc", accent: "#425b70", text: "#172029", soft: "#e9ebed", glass: "rgba(199, 201, 204, 0.72)" }, fontFamily: "geometric", narrative: ["The iPod made a large music library feel small enough to carry. Its click wheel turned browsing into a physical rhythm, and the white silhouette became a new kind of cultural shorthand.", "Then the phone became a screen, a camera, a map, and a window. The important shift was not adding more buttons; it was removing the need to think about the device at all."], artifact: { label: "POCKET / 07", title: "The glass slab", detail: "2007 · multi-touch · one surface, many rooms", glyph: "▱" } },
  { id: "today", years: "2011—now", title: "Design at scale", kicker: "The quiet machine", palette: { bg: "#111820", accent: "#8ad8c0", text: "#f0f3ef", soft: "#202c34", glass: "rgba(17, 24, 32, 0.72)" }, fontFamily: "geometric", narrative: ["Today, the visible product is often only the edge of a much larger system: silicon, software, services, accessibility, and the small decisions that make an object fade into daily life.", "The story keeps moving from spectacle toward intimacy. The most ambitious idea is still the oldest one: powerful tools should leave room for a person to be fully present."], artifact: { label: "SILICON / 26", title: "Power, held lightly", detail: "Today · custom silicon · attention returned to the human", glyph: "✦" } },
];